### ISSUE TITLE
Elastic listen address

### ISSUE THREAD

**Issue by measwel** [strapdata/docker-elassandra#9]
My setup: elassandra runs in a docker container, which runs inside DockerToolbox ( virtual box machine ) which in turn runs inside mac osx - the host. Inside DockerToolbox, the container is reachable on address 0.0.0.0:PORT.

In docker-compose.yml I have:

```
      environment:
          - CASSANDRA_CLUSTER_NAME=arbotti_cluster
          - CASSANDRA_SEEDS=DC1_CASSANDRA_SEED
          - CASSANDRA_PASSWORD_SEEDER=yes
          - CASSANDRA_PASSWORD=password123
          - CASSANDRA_DC=DC1
          - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
          - CASSANDRA_RACK=rack1
      # Exposing ports for inter cluster communication
      expose:
            - 7000
            - 7001
            - 7199
            - 9160
            - 9042
            - 9200
      # Exposing ports on host (docker toolbox) => host_port:docker_port
      ports:
        - "9042:9042"
        - "9200:9200"
```

Elastic search listens on 0.0.0.0:9200
Cassandra listens on 0.0.0.0:9042

In the firewall between the host and DockerToolbox, these ports are open. I can query both without problems from the host.

from the host: curl 0.0.0.0:9200 gives:

{
  "name" : "172.18.0.3", <-- I DO NOT UNDERSTAND WHERE THIS COMES FROM
  "cluster_name" : "arbotti_cluster",
  "cluster_uuid" : "a0aa99db-c6a0-4823-b3de-f6e729a98e5c",
  "version" : {
    "number" : "5.5.0",
    "build_hash" : "37f8692",
    "build_date" : "2018-01-06T20:52:07.026Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}
Inside DockerToolbox: docker ps produces:
e93d0a8e2891 strapdata/elassandra "/docker-entrypoin..." 21 hours ago Up 21 hours 7000-7001/tcp, 7199/tcp, 0.0.0.0:9042->9042/tcp, 9160/tcp, 9300/tcp, 0.0.0.0:9200->9200/tcp a_DC1_CASSANDRA_SEED_1

In my application driver settings I have:

      elasticsearch: {
        apiVersion: '5.5',
        sniffOnStart: true,
        host: 'http://0.0.0.0:9200',
        requestTimeout: 60000
      }
However, the application (running on host) tries to reach elastic by the IP 172.18.0.3 and produces the error:

Elasticsearch ERROR: 2018-01-12T17:27:26Z
Error: Request error, retrying
HEAD http://172.18.0.3:9200/arbotti => socket hang up

It seems as if the driver ignores the elastic search IP setting and gets it from elastic instead. Elastic mentions: "name" : "172.18.0.3" in its response. Should I force elastic to listen on 0.0.0.0 ? Can somebody please explain why elastic mentions the address "172.18.0.3" in its response and how this can be changed?
